Repository learningeconomy/LearnCard, pull requests merged in 2025-07, with the labels that each got.

#708 [LC-1086] Anyone Can Make Children
  .changeset/silly-aliens-tease.md
  packages/learn-card-types/src/lcn.ts
  services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts
  services/learn-card-network/brain-service/src/models/Boost.ts
  tests/e2e/tests/boosts.spec.ts
Labels: 1 min review

#706 Feat: Add copy function to CLI
  .changeset/large-ducks-laugh.md
  packages/learn-card-cli/package.json
  packages/learn-card-cli/src/index.tsx
  pnpm-lock.yaml
Labels: missing-jira, 1 min review

#707 LC-1805 Feat: Universal Inbox
  .changeset/light-terms-rhyme.md
  .github/workflows/deploy.yml
  packages/learn-card-types/src/lcn.ts
  packages/plugins/learn-card-network/src/plugin.ts
  packages/plugins/learn-card-network/src/types.ts
  pnpm-lock.yaml
  services/learn-card-network/brain-service/package.json
  services/learn-card-network/brain-service/serverless.local.yml
  services/learn-card-network/brain-service/serverless.yml
  services/learn-card-network/brain-service/src/accesslayer/contact-method/create.ts
  services/learn-card-network/brain-service/src/accesslayer/contact-method/delete.ts
  services/learn-card-network/brain-service/src/accesslayer/contact-method/read.ts
  services/learn-card-network/brain-service/src/accesslayer/contact-method/relationships/create.ts
  services/learn-card-network/brain-service/src/accesslayer/contact-method/relationships/delete.ts
  services/learn-card-network/brain-service/src/accesslayer/contact-method/relationships/read.ts
  services/learn-card-network/brain-service/src/accesslayer/contact-method/update.ts
  services/learn-card-network/brain-service/src/accesslayer/inbox-credential/create.ts
  services/learn-card-network/brain-service/src/accesslayer/inbox-credential/delete.ts
  services/learn-card-network/brain-service/src/accesslayer/inbox-credential/read.ts
  services/learn-card-network/brain-service/src/accesslayer/inbox-credential/relationships/create.ts
  services/learn-card-network/brain-service/src/accesslayer/inbox-credential/relationships/read.ts
  services/learn-card-network/brain-service/src/accesslayer/inbox-credential/update.ts
  services/learn-card-network/brain-service/src/accesslayer/signing-authority/relationships/create.ts
  services/learn-card-network/brain-service/src/accesslayer/signing-authority/relationships/read.ts
  services/learn-card-network/brain-service/src/accesslayer/signing-authority/relationships/update.ts
  services/learn-card-network/brain-service/src/accesslayer/signing-authority/update.ts
  services/learn-card-network/brain-service/src/app.ts
  services/learn-card-network/brain-service/src/helpers/contact-method.helpers.ts
  services/learn-card-network/brain-service/src/helpers/inbox.helpers.ts
  services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
  services/learn-card-network/brain-service/src/models/ContactMethod.ts
  services/learn-card-network/brain-service/src/models/InboxCredential.ts
  services/learn-card-network/brain-service/src/models/Profile.ts
  services/learn-card-network/brain-service/src/models/index.ts
  services/learn-card-network/brain-service/src/routes/contact-methods.ts
  services/learn-card-network/brain-service/src/routes/inbox.ts
  services/learn-card-network/brain-service/src/routes/profiles.ts
  services/learn-card-network/brain-service/src/routes/workflows.ts
  services/learn-card-network/brain-service/src/services/delivery/adapters/log.adapter.ts
  services/learn-card-network/brain-service/src/services/delivery/adapters/messagebird.adapter.ts
  services/learn-card-network/brain-service/src/services/delivery/adapters/postmark.adapter.ts
  services/learn-card-network/brain-service/src/services/delivery/adapters/twilio.adapter.ts
  services/learn-card-network/brain-service/src/services/delivery/delivery.factory.ts
  services/learn-card-network/brain-service/src/services/delivery/delivery.service.ts
  services/learn-card-network/brain-service/src/services/delivery/helpers/sms.helpers.ts
  services/learn-card-network/brain-service/src/services/registry/adapters/dcc-issuer-registry.adapter.ts
  services/learn-card-network/brain-service/src/services/registry/adapters/whitelist.adapter.ts
  services/learn-card-network/brain-service/src/services/registry/registry.factory.ts
  services/learn-card-network/brain-service/src/services/registry/registry.service.ts
  services/learn-card-network/brain-service/test/contact-method.spec.ts
  services/learn-card-network/brain-service/test/helpers/spies.ts
  services/learn-card-network/brain-service/test/inbox.spec.ts
  services/learn-card-network/brain-service/test/profiles.spec.ts
  services/learn-card-network/brain-service/test/registry.spec.ts
  services/learn-card-network/brain-service/tsconfig.json
  tests/e2e/tests/inbox.spec.ts
Labels: 30 min review

#712 Feat: Add Simple Signing Plugin to CLI
  .changeset/moody-yaks-check.md
  packages/learn-card-cli/package.json
  packages/learn-card-cli/src/index.tsx
  pnpm-lock.yaml
Labels: missing-jira, 1 min review

#727 [LC-1095] Part 3: More VC 2 Fixes
  .changeset/dark-games-melt.md
  packages/learn-card-init/test/index.test.ts
  packages/plugins/vc-templates/src/templates.ts
  packages/plugins/vc/src/vc.ts
  services/learn-card-network/brain-service/src/helpers/boost.helpers.ts
  services/learn-card-network/brain-service/src/routes/boosts.ts
  services/learn-card-network/brain-service/src/routes/contracts.ts
  services/learn-card-network/brain-service/src/routes/index.ts
  services/learn-card-network/simple-signing-service/package.json
  services/learn-card-network/simple-signing-service/src/routes/credentials.ts
  services/learn-card-network/simple-signing-service/src/routes/index.ts
Labels: 5 min review

#730 [LC-1121] Long Loading Times/Neo4j Deadlock
  .changeset/chilly-swans-teach.md
  services/learn-card-network/brain-service/src/accesslayer/boost/create.ts
Labels: 1 min review

#733 [LC-1132] - thumbnail polishes
  .changeset/chilly-eels-breathe.md
  packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
  packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.tsx
  packages/react-learn-card/src/components/svgs/ThreeDotVertical.tsx
  packages/react-learn-card/src/components/svgs/index.ts
  packages/react-learn-card/src/helpers/video.helpers.ts
Labels: 20 min review

#738 fix: Boost Generic Card Content
  .changeset/light-maps-learn.md
  packages/react-learn-card/src/components/BoostGenericCard/BoostGenericCard.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/CertDisplayCardSkillsCount.tsx
  packages/react-learn-card/tailwind.config.js
Labels: 10 min review

#753 [LC-1173] defaultEnabled and autoboost permissions
  .changeset/bumpy-suits-fetch.md
  .changeset/hip-pears-dig.md
  packages/learn-card-types/src/lcn.ts
  services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/create.ts
  services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/update.ts
  services/learn-card-network/brain-service/test/consentflow.spec.ts
  tests/e2e/package.json
  tests/e2e/tests/consentflow.spec.ts
  tests/e2e/tests/helpers/contract.helpers.ts
Labels: 20 min review

#766 [LC-1088] Purge DefaultFace (use first letter of user name if no profile pic)
  .changeset/tired-forks-feel.md
  packages/react-learn-card/src/assets/images/default-face.jpeg
  packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.stories.tsx
  packages/react-learn-card/src/components/BoostSmallCard/BoostSmallCard.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateProfileImageDisplay.tsx
  packages/react-learn-card/src/components/NotificationBoostCard/NotificationBoostCard.stories.tsx
  packages/react-learn-card/src/components/NotificationBoostCard/NotificationBoostCard.tsx
  packages/react-learn-card/src/components/NotificationUserCard/NotificationUserCard.tsx
  packages/react-learn-card/src/components/UserProfilePicture/UserProfilePicture.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/IssueHistoryBox.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.stories.tsx
  packages/react-learn-card/src/components/VCDisplayFrontFace/VCDisplayFrontFace.tsx
  packages/react-learn-card/src/helpers/test.helpers.ts
  services/learn-card-network/brain-service/test/inbox.spec.ts
Labels: 20 min review

#765 Allow using bundler moduleResolution
  .changeset/rotten-numbers-stare.md
  packages/learn-card-bridge-http/tsconfig.json
  packages/learn-card-cli/tsconfig.json
  packages/learn-card-core/package.json
  packages/learn-card-core/tsconfig.json
  packages/learn-card-helpers/tsconfig.json
  packages/learn-card-init/package.json
  packages/learn-card-init/tsconfig.json
  packages/learn-card-network/brain-client/tsconfig.json
  packages/learn-card-network/cloud-client/tsconfig.json
  packages/learn-card-network/simple-signing-client/tsconfig.json
  packages/learn-card-types/tsconfig.json
  packages/plugins/ceramic/tsconfig.json
  packages/plugins/chapi/tsconfig.json
  packages/plugins/claimable-boosts/package.json
  packages/plugins/claimable-boosts/tsconfig.json
  packages/plugins/crypto/tsconfig.json
  packages/plugins/did-web-plugin/tsconfig.json
  packages/plugins/didkey/tsconfig.json
  packages/plugins/didkit/tsconfig.json
  packages/plugins/dynamic-loader/tsconfig.json
  packages/plugins/encryption/tsconfig.json
  packages/plugins/ethereum/tsconfig.json
  packages/plugins/expiration/tsconfig.json
  packages/plugins/idx/tsconfig.json
  packages/plugins/learn-card-network/tsconfig.json
  packages/plugins/learn-card/tsconfig.json
  packages/plugins/learn-cloud/tsconfig.json
  packages/plugins/simple-signing-plugin/package.json
  packages/plugins/simple-signing-plugin/tsconfig.json
  packages/plugins/vc-api/tsconfig.json
  packages/plugins/vc-templates/tsconfig.json
  packages/plugins/vc/tsconfig.json
  packages/plugins/vpqr/tsconfig.json
  packages/react-learn-card/tsconfig.json
Labels: missing-jira, 20 min review

#770 ✨ feat: Git Environments + Staging CI/CD
  .changeset/nice-ligers-wink.md
  .github/actions/setup/action.yml
  .github/workflows/deploy.yml
  .github/workflows/docker-release.yml
  .github/workflows/maids.yml
  .github/workflows/release.yml
  .github/workflows/test.yml
  services/learn-card-network/brain-service/project.json
  services/learn-card-network/brain-service/serverless.yml
  services/learn-card-network/brain-service/src/constants/auth-grant.ts
  services/learn-card-network/learn-cloud-service/project.json
  services/learn-card-network/learn-cloud-service/serverless.yml
  services/learn-card-network/learn-cloud-service/src/constants/xapi.ts
  services/learn-card-network/learn-cloud-service/src/mongo.ts
Labels: missing-jira, 10 min review
