Repository learningeconomy/LearnCard, pull requests merged in 2025-05, with the labels that each got.

#660 Iteration: Restrict Update Auth Grants to Name/Description Only
  .changeset/good-apples-complain.md
  services/learn-card-network/brain-service/src/routes/auth-grants.ts
  services/learn-card-network/brain-service/test/auth-grant.spec.ts
Labels: 5 min review, missing-jira

#659 [LC-895] - Feat: Generate OpenAPI SDK clients Git Action
  .changeset/clean-steaks-float.md
  .changeset/cyan-grapes-dress.md
  .github/workflows/deploy.yml
  .github/workflows/open-api-generator.yml
  packages/open-api-lcn-clients/README.md
Labels: 5 min review

#666 LC-907 - New Onboarding flow + Checklist UI
  .changeset/hot-rockets-agree.md
  packages/learn-card-types/src/lcn.ts
  services/learn-card-network/brain-service/src/models/Profile.ts
  services/learn-card-network/brain-service/src/routes/profiles.ts
  services/learn-card-network/brain-service/src/types/profile.ts
  services/learn-card-network/brain-service/test/profiles.spec.ts
Labels: 1 min review

#662 [LC-894] Multiple Contract Issuers
  .changeset/large-hairs-tap.md
  .changeset/smart-islands-double.md
  .changeset/wicked-crabs-compete.md
  packages/learn-card-types/src/lcn.ts
  packages/plugins/learn-card-network/src/plugin.ts
  packages/plugins/learn-card-network/src/types.ts
  pnpm-lock.yaml
  services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/create.ts
  services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/manageAutoboosts.ts
  services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/read.ts
  services/learn-card-network/brain-service/src/accesslayer/consentflowcontract/relationships/update.ts
  services/learn-card-network/brain-service/src/helpers/consentflow.helpers.ts
  services/learn-card-network/brain-service/src/helpers/did.helpers.ts
  services/learn-card-network/brain-service/src/models/ConsentFlowContract.ts
  services/learn-card-network/brain-service/src/models/ConsentFlowTerms.ts
  services/learn-card-network/brain-service/src/routes/contracts.ts
  services/learn-card-network/brain-service/test/consentflow.spec.ts
  services/learn-card-network/learn-cloud-service/src/accesslayer/credential-record/update.ts
  services/learn-card-network/learn-cloud-service/src/routes/indexPlane.ts
  tests/e2e/tests/consentflow.spec.ts
  tests/e2e/tsconfig.json
Labels: 30 min review

#670 🧹Housekeeping: OpenAPI Docs
  .changeset/nasty-socks-cross.md
  packages/learn-card-types/src/lcn.ts
  services/learn-card-network/brain-service/src/openapi.ts
  services/learn-card-network/brain-service/src/routes/auth-grants.ts
  services/learn-card-network/brain-service/src/routes/contracts.ts
  services/learn-card-network/learn-cloud-service/src/openapi.ts
Labels: 5 min review, missing-jira

#672 [LC-947] BigInt Thing
  .changeset/ten-yaks-leave.md
  packages/plugins/didkit/src/plugin.ts
  tests/e2e/tests/encryption.spec.ts
Labels: 10 min review

#678 Fix: Update Plugins to support CJS
  .changeset/hot-clouds-fetch.md
  packages/learn-card-core/package.json
  packages/learn-card-core/scripts/build.mjs
  packages/learn-card-core/scripts/mixedEntypoint.js
  packages/learn-card-init/package.json
  packages/learn-card-init/scripts/build.mjs
  packages/learn-card-init/scripts/mixedEntypoint.js
  packages/learn-card-init/test/build-step/README.md
  packages/learn-card-init/test/build-step/test-cjs.cjs
  packages/learn-card-init/test/build-step/test-esm.mjs
  packages/learn-card-init/test/build-step/test-types.ts
  packages/plugins/claimable-boosts/package.json
  packages/plugins/claimable-boosts/scripts/build.mjs
  packages/plugins/claimable-boosts/scripts/mixedEntypoint.js
  packages/plugins/simple-signing-plugin/package.json
  packages/plugins/simple-signing-plugin/scripts/build.mjs
  packages/plugins/simple-signing-plugin/scripts/mixedEntypoint.js
Labels: 5 min review, missing-jira

#680 Add untrusted issuer
  packages/learn-card-registries/untrusted/registry.json
Labels: missing-jira, 1 min review
