Repository learningeconomy/LearnCard, pull requests merged in 2025-09, with the labels that each got.

#801 [LC-1332] Stop Hitting Lambda Response Limit with LearnCloud tRPC client
  .changeset/tender-bags-unite.md
  packages/learn-card-network/cloud-client/src/index.ts
Labels: 1 min review

#780 [LC-1242] Invite Updates
  .changeset/wet-drinks-double.md
  packages/plugins/learn-card-network/src/plugin.ts
  packages/plugins/learn-card-network/src/types.ts
  services/learn-card-network/brain-service/CLAUDE.md
  services/learn-card-network/brain-service/src/cache/invites.ts
  services/learn-card-network/brain-service/src/routes/profiles.ts
  services/learn-card-network/brain-service/test/profiles.spec.ts
  tests/e2e/tests/invites.spec.ts
Labels: 30 min review

#805 [Hotfix] KeyAgreement Backwards Compatibility
  .changeset/bright-plants-wash.md
  .changeset/eight-seals-cross.md
  services/learn-card-network/brain-service/src/dids.ts
  services/learn-card-network/learn-cloud-service/src/dids.ts
  services/learn-card-network/simple-signing-service/src/dids.ts
Labels: 5 min review, missing-jira

#808 chore: Add Presentation to DCC interop
  pnpm-lock.yaml
  tests/e2e/package.json
  tests/e2e/tests/interoperability/dcc/credential-verification.spec.ts
Labels: missing-jira, 10 min review

#815 fix: [LC-1357] Broken video attachment and make skill button clickable
  .changeset/smart-chefs-jam.md
  packages/react-learn-card/src/components/Lightbox/Lightbox.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/TopLevelSkill.tsx
Labels: 1 min review

#817 feat: LC-1216 - extend boost context add "previewType"
  .changeset/tender-cameras-rush.md
  packages/learn-card-contexts/boosts/1.0.2.json
  packages/plugins/vc-templates/src/templates.ts
  packages/plugins/vc-templates/src/types.ts
Labels: 5 min review

#825 fix: Add local dev fallback for notification queue
  .changeset/eleven-apes-explain.md
  services/learn-card-network/brain-service/src/helpers/notifications.helpers.ts
Labels: missing-jira, 1 min review
