Repository learningeconomy/LearnCard, pull requests merged in 2025-08, with the labels that each got.

#779 feat: add nx build and test scripts
  CLAUDE.md
  README.md
  package.json
Labels: 5 min review, missing-jira, codex

#781 feat: add whitehall demo issuer
  packages/learn-card-registries/trusted/registry.json
Labels: codex

#782 [LC-1248] & [LC-1254]
  .changeset/cold-rings-rhyme.md
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/MediaAttachmentsBox.tsx
Labels: 1 min review

#776 [LC-1228] countBoostRecipientsWithChildren
  .changeset/shaky-wings-cheer.md
  packages/plugins/learn-card-network/src/plugin.ts
  packages/plugins/learn-card-network/src/types.ts
  services/learn-card-network/brain-service/src/accesslayer/boost/relationships/read.ts
  services/learn-card-network/brain-service/src/routes/boosts.ts
  services/learn-card-network/brain-service/test/boost.countRecipientsWithChildren.spec.ts
  services/learn-card-network/brain-service/test/boosts.spec.ts
  tests/e2e/tests/boosts.spec.ts
Labels: 30 min review
