Repository learningeconomy/LearnCard, pull requests merged in 2025-06, with the labels that each got.

#682 [LC-334] tRPC v11 2nd Attempt
  .changeset/fine-donuts-agree.md
  .changeset/four-areas-grow.md
  .changeset/mean-needles-poke.md
  .changeset/tricky-planes-argue.md
  package.json
  packages/learn-card-core/package.json
  packages/learn-card-network/brain-client/package.json
  packages/learn-card-network/brain-client/src/index.ts
  packages/learn-card-network/cloud-client/package.json
  packages/learn-card-network/cloud-client/src/index.ts
  packages/learn-card-types/src/index.ts
  packages/plugins/simple-signing-plugin/package.json
  pnpm-lock.yaml
  services/learn-card-network/brain-service/lambda.ts
  services/learn-card-network/brain-service/package.json
  services/learn-card-network/brain-service/src/app.ts
  services/learn-card-network/brain-service/src/docker-entry.ts
  services/learn-card-network/brain-service/src/index.ts
  services/learn-card-network/brain-service/src/openapi.ts
  services/learn-card-network/brain-service/src/routes/auth-grants.ts
  services/learn-card-network/brain-service/src/routes/did-metadata.ts
  services/learn-card-network/brain-service/src/routes/index.ts
  services/learn-card-network/brain-service/src/routes/profile-manager.ts
  services/learn-card-network/brain-service/tsc-alias-replacer.cjs
  services/learn-card-network/learn-cloud-service/lambda.ts
  services/learn-card-network/learn-cloud-service/package.json
  services/learn-card-network/learn-cloud-service/src/app.ts
  services/learn-card-network/learn-cloud-service/src/callbackLink.ts
  services/learn-card-network/learn-cloud-service/src/docker-entry.ts
  services/learn-card-network/learn-cloud-service/src/openapi.ts
  services/learn-card-network/learn-cloud-service/src/routes/index.ts
  services/learn-card-network/learn-cloud-service/src/xapi.ts
  services/learn-card-network/learn-cloud-service/tsc-alias-replacer.cjs
  services/learn-card-network/simple-signing-service/package.json
Labels: 10 min review

#690 [LC-1003] Do not Allow Accepting a Credential/Presentation More Than Once
  .changeset/rare-clubs-wash.md
  services/learn-card-network/brain-service/src/accesslayer/credential/relationships/read.ts
  services/learn-card-network/brain-service/src/accesslayer/presentation/relationships/read.ts
  services/learn-card-network/brain-service/src/helpers/credential.helpers.ts
  services/learn-card-network/brain-service/src/helpers/presentation.helpers.ts
  services/learn-card-network/brain-service/test/credentials.spec.ts
  services/learn-card-network/brain-service/test/presentations.spec.ts
  tests/e2e/tests/credentials.spec.ts
  tests/e2e/tests/presentations.spec.ts
Labels: 10 min review

#681 [LC-961] Upgrade Trust Registries
  .changeset/chatty-pears-shake.md
  packages/learn-card-types/src/registries.ts
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/VerifierStateBadgeAndText.tsx
  packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeDisplayCard.tsx
  packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VC2FrontFaceInfo.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VCIDDIsplayCard.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VCIDDisplayFrontFace.tsx
  packages/react-learn-card/src/types/index.ts
Labels: 5 min review

#693 [LC-1044] Enforce Signing Authority Name Restrictions at Creation
  .changeset/metal-actors-compete.md
  services/learn-card-network/brain-service/src/routes/profiles.ts
  services/learn-card-network/brain-service/test/profiles.spec.ts
  tests/e2e/tests/signing-authorities.spec.ts
Labels: 20 min review

#687 [LC-996] Fix certificate width
  .changeset/open-chicken-beg.md
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateDisplayCard.tsx
  packages/react-learn-card/src/components/CertificateDisplayCard/CertificateFrontFace.tsx
  packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeDisplayCard.tsx
  packages/react-learn-card/src/components/MeritBadgeDisplayCard/MeritBadgeFrontFace.tsx
  packages/react-learn-card/src/components/VCDisplayCard2/VCDisplayCard2.stories.tsx
  packages/react-learn-card/src/helpers/test.helpers.ts
Labels: 10 min review

#699 feat: implement Claim Boosts as a VC-API workflow
  .changeset/eight-owls-pump.md
  pnpm-lock.yaml
  services/learn-card-network/brain-service/package.json
  services/learn-card-network/brain-service/src/app.ts
  services/learn-card-network/brain-service/src/routes/workflows.ts
Labels: missing-jira, 20 min review

#705 [LC-1070] OpenAPI Headers Fix
  .changeset/violet-deer-brush.md
  pnpm-lock.yaml
  services/learn-card-network/brain-service/lambda.ts
  services/learn-card-network/brain-service/package.json
  services/learn-card-network/brain-service/src/helpers/shim.ts
  services/learn-card-network/brain-service/src/routes/index.ts
  services/learn-card-network/brain-service/src/routes/profiles.ts
  services/learn-card-network/learn-cloud-service/src/routes/index.ts
Labels: 20 min review
